"""
VisionBoard AI – PDF Exporter
Exports the drawing canvas as a timestamped PDF using reportlab.
"""
import logging
import os
import time
import tempfile
import cv2
import numpy as np
from config import EXPORT_DIR, APP_NAME, APP_VERSION

log = logging.getLogger(__name__)

try:
    from reportlab.pdfgen import canvas as rl_canvas
    from reportlab.lib.pagesizes import landscape, A4
    from reportlab.lib.units import mm
    _REPORTLAB = True
except ImportError:
    _REPORTLAB = False
    log.warning("reportlab not installed — PDF export disabled. Run: pip install reportlab")


class PDFExporter:

    def export(self, drawing_layer: np.ndarray) -> str | None:
        """
        Export *drawing_layer* as a PDF.
        Returns the file path on success, None if reportlab is unavailable.
        """
        if not _REPORTLAB:
            log.error("reportlab missing — cannot export PDF.")
            return None

        ts       = time.strftime("%Y_%m_%d_%H_%M_%S")
        filename = f"VisionBoardAI_{ts}.pdf"
        path     = os.path.join(EXPORT_DIR, filename)

        # Save canvas as a temp PNG so reportlab can embed it
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            tmp_path = tmp.name
        cv2.imwrite(tmp_path, drawing_layer)

        try:
            self._build_pdf(path, tmp_path, ts)
        finally:
            os.unlink(tmp_path)

        log.info("PDF exported: %s", path)
        return path

    # ── Internal ──────────────────────────────────────────────────────────────

    @staticmethod
    def _build_pdf(pdf_path: str, img_path: str, ts: str):
        page_w, page_h = landscape(A4)
        c = rl_canvas.Canvas(pdf_path, pagesize=(page_w, page_h))

        # Header bar
        c.setFillColorRGB(0.059, 0.714, 0.831)   # brand primary
        c.rect(0, page_h - 28*mm, page_w, 28*mm, fill=1, stroke=0)

        # Title
        c.setFillColorRGB(1, 1, 1)
        c.setFont("Helvetica-Bold", 16)
        c.drawString(10*mm, page_h - 16*mm, f"{APP_NAME}  ·  Transform Gestures into Ideas.")

        # Version + timestamp
        c.setFont("Helvetica", 9)
        c.drawRightString(page_w - 10*mm, page_h - 16*mm, f"v{APP_VERSION}  |  {ts.replace('_', '-')}")

        # Drawing image — fill the page below the header
        img_y      = 12*mm
        img_height = page_h - 28*mm - img_y - 4*mm
        img_width  = page_w - 20*mm
        c.drawImage(img_path, 10*mm, img_y, width=img_width, height=img_height,
                    preserveAspectRatio=True, anchor="c")

        # Footer
        c.setFillColorRGB(0.4, 0.4, 0.4)
        c.setFont("Helvetica", 8)
        c.drawCentredString(page_w / 2, 6*mm, f"Generated by {APP_NAME} v{APP_VERSION}")

        c.save()
