"""
VisionBoard AI – Web PDF Export
Returns PDF as raw bytes for st.download_button.
Does NOT write to disk (Streamlit Cloud has an ephemeral filesystem).
"""
import io
import logging
import tempfile
import os
import time
import cv2
import numpy as np
from config import APP_NAME, APP_VERSION

log = logging.getLogger(__name__)

try:
    from reportlab.pdfgen import canvas as rl_canvas
    from reportlab.lib.pagesizes import landscape, A4
    from reportlab.lib.units import mm
    _REPORTLAB = True
except ImportError:
    _REPORTLAB = False
    log.warning("reportlab not installed — PDF export disabled.")


def export_pdf_bytes(drawing_layer: np.ndarray) -> bytes | None:
    """
    Convert *drawing_layer* to a PDF and return it as raw bytes.
    Returns None if reportlab is unavailable.
    """
    if not _REPORTLAB:
        return None

    ts = time.strftime("%Y-%m-%d %H:%M:%S")

    # Write the canvas as a temp PNG (reportlab needs a file path)
    tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
    tmp.close()
    cv2.imwrite(tmp.name, drawing_layer)

    buf = io.BytesIO()
    try:
        _build_pdf(buf, tmp.name, ts)
    finally:
        os.unlink(tmp.name)

    return buf.getvalue()


def _build_pdf(buf: io.BytesIO, img_path: str, ts: str):
    page_w, page_h = landscape(A4)
    c = rl_canvas.Canvas(buf, pagesize=(page_w, page_h))

    # Brand header bar
    c.setFillColorRGB(0.024, 0.714, 0.831)
    c.rect(0, page_h - 28 * mm, page_w, 28 * mm, fill=1, stroke=0)

    c.setFillColorRGB(1, 1, 1)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(10 * mm, page_h - 16 * mm,
                 f"{APP_NAME}  ·  Transform Gestures into Ideas.")

    c.setFont("Helvetica", 9)
    c.drawRightString(page_w - 10 * mm, page_h - 16 * mm,
                      f"v{APP_VERSION}  |  {ts}")

    # Drawing image
    img_y      = 12 * mm
    img_height = page_h - 28 * mm - img_y - 4 * mm
    img_width  = page_w - 20 * mm
    c.drawImage(img_path, 10 * mm, img_y,
                width=img_width, height=img_height,
                preserveAspectRatio=True, anchor="c")

    c.setFillColorRGB(0.4, 0.4, 0.4)
    c.setFont("Helvetica", 8)
    c.drawCentredString(page_w / 2, 6 * mm,
                        f"Generated by {APP_NAME} v{APP_VERSION}")
    c.save()
